#!/usr/bin/env python3
"""
Verify ONNX Export correctness.

Compares embeddings generated by PyTorch vs ONNX Runtime.
"""

import sys
from pathlib import Path
import numpy as np
import logging

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.features.embeddings import CodeBERTEmbedder

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def verify():
    code_snippets = [
        "def hello(): print('world')",
        "class Foo: pass",
        "import os; os.path.join('a', 'b')"
    ]
    
    # 1. PyTorch Embeddings
    print("\n🔥 Generating PyTorch embeddings...")
    pt_embedder = CodeBERTEmbedder(use_onnx=False)
    pt_embs = pt_embedder.get_embeddings_batch(code_snippets, show_progress=False)
    
    # 2. ONNX Embeddings
    print("\n🚀 Generating ONNX embeddings...")
    try:
        onnx_embedder = CodeBERTEmbedder(use_onnx=True)
        onnx_embs = onnx_embedder.get_embeddings_batch(code_snippets, show_progress=False)
    except Exception as e:
        print(f"❌ Failed to load ONNX embedder: {e}")
        return False

    # 3. Compare
    print("\n📊 Comparison:")
    max_diff = np.max(np.abs(pt_embs - onnx_embs))
    avg_diff = np.mean(np.abs(pt_embs - onnx_embs))
    
    print(f"   Max Difference: {max_diff:.6f}")
    print(f"   Avg Difference: {avg_diff:.6f}")
    
    # Cosine Similarity between corresponding vectors
    print("   Cosine Similarities:")
    for i in range(len(code_snippets)):
        v1 = pt_embs[i]
        v2 = onnx_embs[i]
        cos_sim = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
        print(f"     Snippet {i+1}: {cos_sim:.6f}")
        
        if cos_sim < 0.999:
            print("❌ content mismatch!")
            return False

    if max_diff < 1e-4:
        print("\n✅ PASSED: ONNX model matches PyTorch model.")
        return True
    else:
        print("\n⚠️ WARNING: Differences computed. Please check if acceptable.")
        return True # Soft pass for small float diffs

if __name__ == "__main__":
    success = verify()
    sys.exit(0 if success else 1)
